language: cpp
compiler:
  - gcc
  - clang
install:
  - export CI_ROS_DISTRO=hydro
  - echo $CI_ROS_DISTRO
# Add ROS repositories
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
# Install and initialize rosdep
  - sudo apt-get install python-rosdep
  - sudo `which rosdep` init
  - rosdep update
# Use rosdep to install rviz's dependencies
  - rosdep install --default-yes --from-paths ./ --rosdistro $CI_ROS_DISTRO
script:
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=./install
  - make -j1
  - make -j1 run_tests
  - catkin_test_results .
  - make -j1 install
notifications:
  email: false
